name: sea-ice-prediction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - pytorch-cuda=11.7
  - pytorch=2.0.0
  - xarray=2023.4.2
  - rioxarray=0.14.1
  - tqdm
  - pip:
      - torchvision==0.15.0